# Generated by Django 2.0.6 on 2018-06-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1024)),
                ('userid', models.IntegerField(default=114514)),
                ('useridnickname', models.CharField(max_length=50)),
                ('answercount', models.IntegerField(default=0)),
                ('up', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('display', models.BooleanField(default=1)),
            ],
        ),
    ]
