# Generated by Django 2.0.6 on 2018-06-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_under_flow', '0002_question_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
