# Generated by Django 2.0.6 on 2018-06-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_under_flow', '0003_question_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='update_time',
            field=models.DateTimeField(verbose_name='更新时间'),
        ),
    ]
