# Generated by Django 2.0.6 on 2018-06-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_under_flow', '0004_auto_20180614_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
    ]
