# Generated by Django 2.0.6 on 2018-06-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_under_flow', '0005_auto_20180614_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('userid', models.IntegerField(default=114514)),
                ('questionid', models.IntegerField(default=114514)),
                ('useridnickname', models.CharField(max_length=50)),
                ('up', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('display', models.BooleanField(default=1)),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
    ]
