# Generated by Django 2.0.6 on 2018-06-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_under_flow', '0006_auto_20180614_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
    ]
