# Generated by Django 2.0.6 on 2018-06-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_under_flow', '0008_auto_20180615_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='loushu',
            field=models.IntegerField(default=1),
        ),
    ]
