# Generated by Django 2.0.6 on 2018-06-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack_under_flow', '0010_auto_20180616_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='down',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='up',
        ),
        migrations.RemoveField(
            model_name='question',
            name='down',
        ),
        migrations.RemoveField(
            model_name='question',
            name='up',
        ),
    ]
