# Generated by Django 2.0.6 on 2018-06-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_under_flow', '0012_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='questions',
            field=models.ManyToManyField(related_name='tag_questions', to='stack_under_flow.question'),
        ),
    ]
