# Generated by Django 2.0.6 on 2018-06-17 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack_under_flow', '0013_auto_20180617_1950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tags',
            new_name='tag',
        ),
    ]
