# Generated by Django 2.0.6 on 2018-06-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_under_flow', '0014_auto_20180617_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='qcountintag',
            field=models.IntegerField(default=0),
        ),
    ]
