# Generated by Django 2.0.6 on 2018-06-18 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stack_under_flow', '0015_tag_qcountintag'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='contentstring',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='contentstring',
            field=models.CharField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
    ]
