# Generated by Django 2.0.6 on 2018-06-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_under_flow', '0017_auto_20180618_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='giftpoint',
            field=models.IntegerField(default=0),
        ),
    ]
