# Generated by Django 2.0.6 on 2018-06-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_under_flow', '0018_question_giftpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendmessage_usernickname', models.CharField(max_length=500)),
                ('receivemessage_usernickname', models.CharField(max_length=500)),
                ('message_content', models.CharField(max_length=5000)),
                ('message_sendtime', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
            },
        ),
    ]
