# Generated by Django 2.0.6 on 2018-06-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_under_flow', '0019_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_questionid',
            field=models.IntegerField(default=0),
        ),
    ]
