# Generated by Django 2.0.6 on 2018-06-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_under_flow', '0021_message_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_questiontitle',
            field=models.CharField(default='测试', max_length=500),
        ),
    ]
