# Generated by Django 2.0.6 on 2018-06-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_under_flow', '0022_message_message_questiontitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='beforemarkdown',
            field=models.CharField(default='# 555', max_length=5000),
        ),
    ]
