# Generated by Django 2.0.6 on 2018-06-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_under_flow', '0023_question_beforemarkdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rewrite_time',
            field=models.DateTimeField(auto_now=True, verbose_name='编辑时间'),
        ),
    ]
