# Generated by Django 2.0.6 on 2018-06-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_unlikecount_unlikerecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unlikecount',
            old_name='liked_num',
            new_name='unliked_num',
        ),
        migrations.RenameField(
            model_name='unlikerecord',
            old_name='liked_time',
            new_name='unliked_time',
        ),
    ]
